{
 "title": "Nessie Benchmark",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info_total{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nessie Commit (time)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(nessie_benchmark_action_seconds_bucket{application=\"Nessie-Benchmark\", action=~\"Nessie: Commit-.*\"}[1m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nessie_benchmark_action_seconds_bucket{application=\"Nessie-Benchmark\", action=~\"Nessie: Commit-.*\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nessie_benchmark_action_seconds_bucket{application=\"Nessie-Benchmark\", action=~\"Nessie: Commit-.*\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(nessie_benchmark_action_seconds_bucket{application=\"Nessie-Benchmark\", action=~\"Nessie: Commit-.*\"}[1m])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "max(nessie_benchmark_action_seconds_max{application=\"Nessie-Benchmark\", action=~\"Nessie: Commit-.*\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Nessie Commit (rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nessie_benchmark_action_seconds_count{application=\"Nessie-Benchmark\", action=~\"Nessie: Commit-.*\"}[1m]))",
     "legendFormat": "rate {{status}}"
    }
   ]
  },
  {
   "title": "Nessie Get Commit Log (time)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(nessie_benchmark_action_seconds_bucket{application=\"Nessie-Benchmark\", action=~\"Nessie: Get commit log.*\"}[1m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nessie_benchmark_action_seconds_bucket{application=\"Nessie-Benchmark\", action=~\"Nessie: Get commit log.*\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nessie_benchmark_action_seconds_bucket{application=\"Nessie-Benchmark\", action=~\"Nessie: Get commit log.*\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(nessie_benchmark_action_seconds_bucket{application=\"Nessie-Benchmark\", action=~\"Nessie: Get commit log.*\"}[1m])) by (le))",
     "legendFormat": "p999"
    },
    {
     "expr": "max(nessie_benchmark_action_seconds_max{application=\"Nessie-Benchmark\", action=~\"Nessie: Get commit log.*\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Nessie Get Commit Log (rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nessie_benchmark_action_seconds_count{application=\"Nessie-Benchmark\", action=~\"Nessie: Get commit log.*\"}[1m]))",
     "legendFormat": "rate {{status}}"
    }
   ]
  },
  {
   "title": "Benchmark Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nessie_benchmark_total_duration_seconds_max",
     "legendFormat": "Total Duration"
    }
   ]
  },
  {
   "title": "Active Benchmark Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nessie_benchmark_active_users", "legendFormat": "users" }
   ]
  }
 ]
}