name: 'Save incremental Gradle caches'
description: 'Save incremental Gradle caches'
inputs:
  job-name:
    description: 'job name'
  java-version:
    description: 'Java version'
    default: '21'
runs:
  using: "composite"
  steps:
    - name: Prepare Gradle caches archive
      shell: bash
      run: |
        if [[ -d ~/.gradle/caches/ ]] ; then
          echo "::group::Gradle caches / identify updated cache items"

          cd ~/.gradle/caches/

          echo "Gradle caches/ contains $(find . -type f | wc -l) files"
          # Identify the added and changed files in caches/.

          echo "Identifying changed/added files..."
          AGE_SECS=$(($(date +%s) - $(cat ~/caches-prepared-at-epoch)))
          echo "Build started ~ $AGE_SECS seconds ago"
          AGE_MINS=$(($AGE_SECS / 60 + 1))
          echo " ... assuming that is ~ $AGE_MINS minutes"
          # This lists all relevant files that have been created or modified during by the Gradle
          # runs of the current job.
          find . -mmin -$AGE_MINS -type f '(' \
            -path './[0-9]*/kotlin-dsl/*' -or \
            -path './jars-*/*' -or \
            -path './modules-*/files-*/*' -or \
            -path './build-cache-*/*' \
            ')' | grep -v '[.]lock$'  > ~/ci-gradle-caches-diff || true
          echo "Identified $(wc -l < ~/ci-gradle-caches-diff) changed/added files in caches/"

          # Only call 'tar', if there is some difference
          # Note: actions/upload-artifact takes care of compressing the artifact, no need to bug the CPU here
          echo "Creating artifact (if necessary)..."
          if [[ -s ~/ci-gradle-caches-diff ]] ; then
            tar --create --ignore-failed-read --file ~/ci-gradle-caches-${{ inputs.job-name }}-${{ inputs.java-version }}.tar -T ~/ci-gradle-caches-diff
            ls -al ~/ci-gradle-caches-${{ inputs.job-name }}-${{ inputs.java-version }}.tar
          fi
          echo "::endgroup::"
        fi
    - name: Archive incremental Gradle caches
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: ci-gradle-caches-${{ inputs.job-name }}-${{ inputs.java-version }}
        path: ~/ci-gradle-caches-${{ inputs.job-name }}-${{ inputs.java-version }}.tar
        if-no-files-found: ignore
        retention-days: 1
