version: 1
creds:
  - registry: docker.io
    user: "{{env \"DOCKER_USERNAME\"}}"
    pass: "{{env \"DOCKER_TOKEN\"}}"
  - registry: quay.io
    user: "{{env \"QUAY_IO_USER\"}}"
    pass: "{{env \"QUAY_IO_TOKEN\"}}"
  - registry: ghcr.io
    user: "$"
    pass: "{{env \"GHCR_IO_TOKEN\"}}"
defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 2
sync:
  # Server
  - source: ghcr.io/projectnessie/nessie-unstable
    target: quay.io/projectnessie/nessie-unstable
    type: repository
    tags:
      allow:
      - "latest.*"
      - "0[.][567]\\d+[.].*"
  - source: ghcr.io/projectnessie/nessie-unstable
    target: docker.io/projectnessie/nessie-unstable
    type: repository
    tags:
      allow:
      - "latest.*"
      - "0[.][567]\\d+[.].*"
  - source: ghcr.io/projectnessie/nessie
    target: quay.io/projectnessie/nessie
    type: repository
  - source: ghcr.io/projectnessie/nessie
    target: docker.io/projectnessie/nessie
    type: repository
  # GC Tool
  - source: ghcr.io/projectnessie/nessie-gc-unstable
    target: quay.io/projectnessie/nessie-gc-unstable
    type: repository
    tags:
      allow:
      - "latest.*"
      - "0[.][567]\\d+[.].*"
  - source: ghcr.io/projectnessie/nessie-gc-unstable
    target: docker.io/projectnessie/nessie-gc-unstable
    type: repository
    tags:
      allow:
      - "latest.*"
      - "0[.][567]\\d+[.].*"
  - source: ghcr.io/projectnessie/nessie-gc
    target: quay.io/projectnessie/nessie-gc
    type: repository
  - source: ghcr.io/projectnessie/nessie-gc
    target: docker.io/projectnessie/nessie-gc
    type: repository
