version: 1
creds:
  - registry: quay.io
    user: "{{env \"QUAY_IO_USER\"}}"
    pass: "{{env \"QUAY_IO_TOKEN\"}}"
  - registry: ghcr.io
    user: "$"
    pass: "{{env \"GHCR_IO_TOKEN\"}}"
defaults:
  ratelimit:
    min: 100
    retry: 15m
  parallel: 2
sync:
  # Server
  - source: ghcr.io/projectnessie/nessie-unstable
    target: quay.io/projectnessie/nessie-unstable
    type: repository
  - source: ghcr.io/projectnessie/nessie
    target: quay.io/projectnessie/nessie
    type: repository
  # GC Tool
  - source: ghcr.io/projectnessie/nessie-gc-unstable
    target: quay.io/projectnessie/nessie-gc-unstable
    type: repository
  - source: ghcr.io/projectnessie/nessie-gc
    target: quay.io/projectnessie/nessie-gc
    type: repository
  # Server Admin Tool
  - source: ghcr.io/projectnessie/nessie-server-admin-unstable
    target: quay.io/projectnessie/nessie-server-admin-unstable
    type: repository
  - source: ghcr.io/projectnessie/nessie-server-admin
    target: quay.io/projectnessie/nessie-server-admin
    type: repository
  # CLI
  - source: ghcr.io/projectnessie/nessie-cli-unstable
    target: quay.io/projectnessie/nessie-cli-unstable
    type: repository
  - source: ghcr.io/projectnessie/nessie-cli
    target: quay.io/projectnessie/nessie-cli
    type: repository
  # NOTE: When adding new images, make sure that the repository exist on quay.io!
  # See also the note about ghcr.io in .github/workflows/*-publish.yml about ghcr.io.
