name: 'Setup Java/Gradle'
description: 'Sets up Java + Gradle'
inputs:
  java-version:
    required: false
    default: '21'
    description: 'Java version, defaults to 21'
  additional-java-version:
    required: false
    default: ''
    description: 'Additional Java version to install, default is none'
  gpg-private-key:
    required: false
    default: ''
    description: 'gpg key, needed when publishing to sonatype'
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
      with:
        distribution: 'temurin'
        java-version: |
          ${{ inputs.additional-java-version }}
          ${{ inputs.java-version }}
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_OSSRH_TOKEN
        gpg-private-key: ${{ inputs.gpg-private-key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Setup testcontainers.properties
      shell: bash
      run: |
        cat > ~/.testcontainers.properties <<!
        # Disable startup checks - speeds up test execution by a few seconds.
        # See https://www.testcontainers.org/features/configuration/#disabling-the-startup-checks
        checks.disable=true
        !
