FROM nektos/act-environments-ubuntu:18.04

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0 ; \
    apt-add-repository https://cli.github.com/packages ; \
    apt-get update ; \
    apt-get install -y gh
