/*
 * Copyright (C) 2020 Dremio
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dremio.nessie.versioned.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.TreeMap;

import com.dremio.nessie.versioned.Key;
import com.dremio.nessie.versioned.store.Entity;
import com.dremio.nessie.versioned.store.Id;
import com.google.common.base.Charsets;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;

/**
 * This utility class generates sample objects mapping to each enumerate in
 * {@link com.dremio.nessie.versioned.store.ValueType}.
 * It is intended to be a central place for test data generation used by multiple test suites.
 */
public class SampleEntities {
  /**
   * Create a Sample L1 entity.
   * @return sample L1 entity.
   */
  public static L1 createL1() {
    final List<Id> fragments = ImmutableList.of(createId(), createId(), createId());
    final List<KeyMutation> mutations = ImmutableList.of(
        KeyMutation.KeyAddition.of(new InternalKey(Key.of("a", createString(8), createString(9))))
    );

    final List<Entity> deltaIds = new ArrayList<>(L1.SIZE);
    for (int i = 0; i < L1.SIZE; i++) {
      deltaIds.add(createIdEntity());
    }

    return new L1(
      createId(),
      IdMap.fromEntity(Entity.ofList(deltaIds), L1.SIZE),
      null, // Don't specify the ID, let it be autogenerated.
      new KeyList.CompleteList(fragments, mutations),
      ParentList.fromEntity(Entity.ofList(createIdEntity())));
  }

  /**
   * Create a Sample L2 entity.
   * @return sample L2 entity.
   */
  public static L2 createL2() {
    final List<Entity> treeList = new ArrayList<>(L2.SIZE);
    for (int i = 0; i < L2.SIZE; i++) {
      treeList.add(createIdEntity());
    }

    final Map<String, Entity> attributeMap = new HashMap<>();
    attributeMap.put("id", createIdEntity());
    attributeMap.put("tree", Entity.ofList(treeList));

    return L2.SCHEMA.mapToItem(attributeMap);
  }

  /**
   * Create a Sample L3 entity.
   * @return sample L3 entity.
   */
  public static L3 createL3() {
    final int size = 100;
    final TreeMap<InternalKey, PositionDelta> keys = new TreeMap<>();
    for (int i = 0; i < size; ++i) {
      keys.put(new InternalKey(Key.of(
          createString(5), createString(9), String.valueOf(i))), PositionDelta.of(i, createId()));
    }
    return new L3(keys);
  }

  /**
   * Create a Sample Fragment entity.
   * @return sample Fragment entity.
   */
  public static Fragment createFragment() {
    final int size = 10;
    final List<Entity> keyList = new ArrayList<>(size);
    for (int i = 0; i < size; i++) {
      keyList.add(Entity.ofList(
          createStringEntity(5), createStringEntity(8), Entity.ofString(String.valueOf(i))));
    }

    final Map<String, Entity> attributeMap = new HashMap<>();
    attributeMap.put("id", createIdEntity());
    attributeMap.put("keys", Entity.ofList(keyList));

    return Fragment.SCHEMA.mapToItem(attributeMap);
  }

  /**
   * Create a Sample Branch (InternalRef) entity.
   * @return sample Branch (InternalRef) entity.
   */
  public static InternalRef createBranch() {
    final List<Entity> treeList = new ArrayList<>(L1.SIZE);
    for (int i = 0; i < L1.SIZE; i++) {
      treeList.add(createIdEntity());
    }

    // Two commits, one with a DELTA and one without.
    final List<Entity> commitList = new ArrayList<>(2);
    commitList.add(Entity.ofMap(ImmutableMap.of(
        "id", createIdEntity(),
        "commit", createIdEntity(),
        "parent", createIdEntity()
    )));
    commitList.add(Entity.ofMap(ImmutableMap.of(
        "id", createIdEntity(),
        "commit", createIdEntity(),
        "deltas", Entity.ofList(Entity.ofMap(ImmutableMap.of(
            "position", Entity.ofNumber(1),
            "old", createIdEntity(),
            "new", createIdEntity()
        ))),
        "keys", Entity.ofList(Entity.ofMap(ImmutableMap.of("a",
            Entity.ofList(createStringEntity(8), createStringEntity(8)))))
    )));

    final Map<String, Entity> attributeMap = new HashMap<>();
    attributeMap.put(InternalRef.TYPE, Entity.ofString("b"));
    final String name = createString(10);
    attributeMap.put("name", Entity.ofString(name));
    attributeMap.put("id", Id.build(name).toEntity());
    attributeMap.put("tree", Entity.ofList(treeList));
    attributeMap.put("metadata", createIdEntity());
    attributeMap.put("commits", Entity.ofList(commitList));

    return InternalRef.SCHEMA.mapToItem(attributeMap);
  }

  /**
   * Create a Sample Tag (InternalRef) entity.
   * @return sample Tag (InternalRef) entity.
   */
  public static InternalRef createTag() {
    final Map<String, Entity> attributeMap = new HashMap<>();
    attributeMap.put(InternalRef.TYPE, Entity.ofString("t"));
    attributeMap.put("id", createIdEntity());
    attributeMap.put("name", Entity.ofString("tagName"));
    attributeMap.put("commit", createIdEntity());

    return InternalRef.SCHEMA.mapToItem(attributeMap);
  }

  /**
   * Create a Sample CommitMetadata entity.
   * @return sample CommitMetadata entity.
   */
  public static InternalCommitMetadata createCommitMetadata() {
    final Map<String, Entity> attributeMap = new HashMap<>();
    attributeMap.put("id", createIdEntity());
    attributeMap.put("value", Entity.ofBinary(createBinary(6)));

    return InternalCommitMetadata.SCHEMA.mapToItem(attributeMap);
  }

  /**
   * Create a Sample Value entity.
   * @return sample Value entity.
   */
  public static InternalValue createValue() {
    final Map<String, Entity> attributeMap = new HashMap<>();
    attributeMap.put("id", createIdEntity());
    attributeMap.put("value", Entity.ofBinary(createBinary(7)));

    return InternalValue.SCHEMA.mapToItem(attributeMap);
  }

  /**
   * Create an array of random bytes.
   * @param numBytes the size of the array.
   * @return the array of random bytes.
   */
  public static byte[] createBinary(int numBytes) {
    final byte[] buffer = new byte[numBytes];
    new Random().nextBytes(buffer);
    return buffer;
  }

  /**
   * Create a String of random characters.
   * @param numChars the size of the String.
   * @return the String of random characters.
   */
  public static String createString(int numChars) {
    final byte[] array = new byte[numChars];
    new Random().nextBytes(array);
    return new String(array, Charsets.UTF_8);
  }

  private static Id createId() {
    return Id.of(createBinary(20));
  }

  private static Entity createIdEntity() {
    return Entity.ofBinary(createBinary(20));
  }

  private static Entity createStringEntity(int numChars) {
    return Entity.ofString(createString(numChars));
  }
}
