name: 'Setup runner'
runs:
  using: "composite"
  steps:
    - name: Capture test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-results
        path: |
          **/target/surefire-reports/*
          **/target/failsafe-reports/*
          **/build/reports/*
          **/build/test-results/*
    - name: Capture Gatling simulation logs
      uses: actions/upload-artifact@v2
      with:
        name: gatling-logs
        path: perftest/simulations/target/gatling/*/simulation.log
    - uses: codecov/codecov-action@v1
      with:
        flags: java
        files: |
          code-coverage/target/site/jacoco-aggregate-all/jacoco.xml
