####
#
# This Dockerfile is used in order to build a container that runs a Quarkus application in JVM mode.
#
# Before building the container image, build the Quarkus application using the "fast-jar" packaging,
# which is the default packaging type. For example:
#    ./gradlew :nessie-quarkus:quarkusBuild
#
# FOLLOWING DESCRIPTION AND CONTENT "BORROWED" FROM QUARKUS SOURCE.
# source file: https://github.com/quarkusio/quarkus/blob/main/integration-tests/maven/src/test/resources-filtered/projects/codegen-config-factory/app/src/main/docker/Dockerfile.jvm
#
# This image uses the `run-java.sh` script to run the application.
# This scripts computes the command line to execute your Java application, and
# includes memory/GC tuning.
#
# (See site/docs/try/configuration.md)
#
# Useful links to base images and respective Dockerfiles:
# https://catalog.redhat.com/software/containers/ubi9/openjdk-21-runtime/6501ce769a0d86945c422d5f?architecture=amd64&image=66c2c0999bba0b8440407e86&container-tabs=dockerfile
# https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?container-tabs=dockerfile
#
###

FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24-2

LABEL org.opencontainers.image.source=https://github.com/projectnessie/nessie
LABEL org.opencontainers.image.description="Projectnessie Nessie Core Server"
LABEL org.opencontainers.image.licenses=Apache-2.0

ENV LANGUAGE='en_US:en'

USER root
RUN groupadd --gid 10001 nessie \
      && useradd --uid 10000 --gid nessie nessie \
      && chown -R nessie:nessie /opt/jboss/container \
      && chown -R nessie:nessie /deployments

USER nessie
WORKDIR /home/nessie
ENV USER=nessie
ENV UID=10000
ENV HOME=/home/nessie

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=nessie:nessie build/quarkus-app/lib/ /deployments/lib/
COPY --chown=nessie:nessie build/quarkus-app/*.jar /deployments/
COPY --chown=nessie:nessie build/quarkus-app/app/ /deployments/app/
COPY --chown=nessie:nessie build/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 19120

ENV AB_JOLOKIA_OFF=""
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
