FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.20-2

LABEL org.opencontainers.image.source=https://github.com/projectnessie/nessie
LABEL org.opencontainers.image.description="Projectnessie CLI"
LABEL org.opencontainers.image.licenses=Apache-2.0

ARG VERSION

ENV LANGUAGE='en_US:en'

COPY --chown=185 build/libs/nessie-cli-$VERSION.jar /nessie-cli.jar

USER 185

ENTRYPOINT [ "java", "-jar", "/nessie-cli.jar" ]
