FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.20-2.1721752928

LABEL org.opencontainers.image.source=https://github.com/projectnessie/nessie
LABEL org.opencontainers.image.description="Projectnessie CLI"
LABEL org.opencontainers.image.licenses=Apache-2.0

ARG VERSION

ENV LANGUAGE='en_US:en'

USER root
RUN groupadd --gid 1001 nessie \
      && useradd --uid 1001 --gid nessie nessie \
      && chown -R nessie:nessie /opt/jboss/container \
      && chown -R nessie:nessie /deployments

USER 1001
WORKDIR /home/nessie
ENV USER=nessie
ENV UID=1001
ENV HOME=/home/nessie

COPY --chown=1001:1001 build/libs/nessie-cli-$VERSION.jar /nessie-cli.jar

ENTRYPOINT [ "java", "-jar", "/nessie-cli.jar" ]
