FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24-2

LABEL org.opencontainers.image.source=https://github.com/projectnessie/nessie
LABEL org.opencontainers.image.description="Projectnessie GC Tool"
LABEL org.opencontainers.image.licenses=Apache-2.0

ENV LANGUAGE='en_US:en'

USER root
RUN groupadd --gid 10001 nessie \
      && useradd --uid 10000 --gid nessie nessie \
      && chown -R nessie:nessie /opt/jboss/container \
      && chown -R nessie:nessie /deployments

USER nessie
WORKDIR /home/nessie
ENV USER=nessie
ENV UID=10000
ENV HOME=/home/nessie

COPY --chown=nessie:nessie build/executable/nessie-gc.jar /

ENTRYPOINT [ "java", "-jar", "/nessie-gc.jar" ]
