FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.18-4@sha256:399a4169b3474e949597390191faab28f404e4cacc816de1b33fa389b48f929f

LABEL org.opencontainers.image.source=https://github.com/projectnessie/nessie
LABEL org.opencontainers.image.description="Projectnessie Sever Admin Tool"
LABEL org.opencontainers.image.licenses=Apache-2.0

ENV LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 build/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 build/quarkus-app/*.jar /deployments/
COPY --chown=185 build/quarkus-app/app/ /deployments/app/
COPY --chown=185 build/quarkus-app/quarkus/ /deployments/quarkus/

USER 185
ENTRYPOINT [ "java", "-jar", "/deployments/quarkus-run.jar" ]
