name: 'Incremental Gradle build cache prepare'
description: 'Prepare to save incremental Gradle build cache'
inputs:
  cache-read-only:
    description: 'Gradle cache read only'
    default: 'true'
  java-version:
    description: 'Java version'
    default: '21'
  job-id:
    description: 'Job name to prefer'
    default: 'nessie-ci'
  job-instance:
    description: 'Job instance to prefer'
    default: 'ci'
runs:
  using: "composite"
  steps:
    - name: Prep env
      shell: bash
      run: |
        echo "GRADLE_BUILD_ACTION_CACHE_KEY_ENVIRONMENT=java-${{ inputs.java-version }}" >> ${GITHUB_ENV}
        echo "GRADLE_BUILD_ACTION_CACHE_KEY_JOB=${{ inputs.job-id }}" >> ${GITHUB_ENV}
        if [[ -n "${{ inputs.no-daemon }}" ]] ; then
          echo "G_DAEMON_FLAG=--no-daemon" >> ${GITHUB_ENV}
        fi
        if [[ -n "${{ inputs.job-instance }}" ]] ; then
          echo "GRADLE_BUILD_ACTION_CACHE_KEY_JOB_INSTANCE=${{ inputs.job-instance }}" >> ${GITHUB_ENV}
        fi

    - name: Configure Gradle cache retention settings
      # Without these settings, the Gradle Setup action will evict effectively all "restored incremental" entries,
      # as it will remove all cache entries created before the start-time of the "Store Gradle Cache" job.
      # The total size of GitHub caches for each repository is limited to 10GB, which means that we have to use
      # more aggressive retention settings to keep the size of the Gradle cache stored in GitHub at an appropriate
      # size.
      shell: bash
      run: |
        mkdir -p ~/.gradle/init.d
        cat > ~/.gradle/init.d/cache-settings.gradle.kts <<!
        beforeSettings {
          caches {
            releasedWrappers.setRemoveUnusedEntriesAfterDays(5)
            snapshotWrappers.setRemoveUnusedEntriesAfterDays(1)
            downloadedResources.setRemoveUnusedEntriesAfterDays(2)
            createdResources.setRemoveUnusedEntriesAfterDays(5)
            buildCache.setRemoveUnusedEntriesAfterDays(5)
          }
        }
        !

    - name: Gradle / Setup
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5
      with:
        cache-read-only: ${{ inputs.cache-read-only }}
        validate-wrappers: false

    - name: Gradle / Init
      shell: bash
      run: ./gradlew -h

    - name: Download existing workflow artifacts
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
      # Just in case, don't know the exact inner workings of Gradle's build cache and whether
      # the download-action complains about duplicate files.
      continue-on-error: true
      with:
        path: ~/downloaded-artifacts/

    - name: Extract caches
      shell: bash
      run: |
        echo "::group::Gradle build cache / add incremental updates"
        mkdir -p ~/.gradle/caches/

        if [[ -d ~/downloaded-artifacts/ ]] ; then
          find ~/downloaded-artifacts/ -type f -name "ci-gradle-caches-*-${{ inputs.java-version }}.tar" | while read arch ; do
            echo "Adding archive content from $arch ..."
            (cd ~/.gradle/caches/ ; tar xf $arch --atime-preserve)
          done
        else
          echo "No previous build cache artifacts downloaded."
        fi
        
        date +%s > ~/caches-prepared-at-epoch

        echo "::endgroup::"
