/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorizationRule
 */
export interface AuthorizationRule {
    /**
     * 
     * @type {boolean}
     * @memberof AuthorizationRule
     */
    pathRule?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthorizationRule
     */
    referenceRule?: boolean;
}

export function AuthorizationRuleFromJSON(json: any): AuthorizationRule {
    return AuthorizationRuleFromJSONTyped(json, false);
}

export function AuthorizationRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizationRule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pathRule': !exists(json, 'pathRule') ? undefined : json['pathRule'],
        'referenceRule': !exists(json, 'referenceRule') ? undefined : json['referenceRule'],
    };
}

export function AuthorizationRuleToJSON(value?: AuthorizationRule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pathRule': value.pathRule,
        'referenceRule': value.referenceRule,
    };
}


