/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentsKey
 */
export interface ContentsKey {
    /**
     * 
     * @type {Array<string>}
     * @memberof ContentsKey
     */
    elements?: Array<string>;
}

export function ContentsKeyFromJSON(json: any): ContentsKey {
    return ContentsKeyFromJSONTyped(json, false);
}

export function ContentsKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentsKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elements': !exists(json, 'elements') ? undefined : json['elements'],
    };
}

export function ContentsKeyToJSON(value?: ContentsKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elements': value.elements,
    };
}


