/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DeltaLakeTable,
    HiveDatabase,
    HiveTable,
    IcebergSnapshot,
    SqlView,
    DeltaLakeTableFromJSONTyped,
    DeltaLakeTableToJSON,
    HiveDatabaseFromJSONTyped,
    HiveDatabaseToJSON,
    HiveTableFromJSONTyped,
    HiveTableToJSON,
    IcebergSnapshotFromJSONTyped,
    IcebergSnapshotToJSON,
    SqlViewFromJSONTyped,
    SqlViewToJSON,
} from './';

/**
 * @type Contents
 * 
 * @export
 */
export type Contents = { type: 'DELTA_LAKE_TABLE' } & DeltaLakeTable | { type: 'HIVE_DATABASE' } & HiveDatabase | { type: 'HIVE_TABLE' } & HiveTable | { type: 'ICEBERG_SNAPSHOT' } & IcebergSnapshot | { type: 'VIEW' } & SqlView;

export function ContentsFromJSON(json: any): Contents {
    return ContentsFromJSONTyped(json, false);
}

export function ContentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contents {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'DELTA_LAKE_TABLE':
            return {...DeltaLakeTableFromJSONTyped(json, true), type: 'DELTA_LAKE_TABLE'};
        case 'HIVE_DATABASE':
            return {...HiveDatabaseFromJSONTyped(json, true), type: 'HIVE_DATABASE'};
        case 'HIVE_TABLE':
            return {...HiveTableFromJSONTyped(json, true), type: 'HIVE_TABLE'};
        case 'ICEBERG_SNAPSHOT':
            return {...IcebergSnapshotFromJSONTyped(json, true), type: 'ICEBERG_SNAPSHOT'};
        case 'VIEW':
            return {...SqlViewFromJSONTyped(json, true), type: 'VIEW'};
        default:
            throw new Error(`No variant of Contents exists with 'type=${json['type']}'`);
    }
}

export function ContentsToJSON(value?: Contents | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'DELTA_LAKE_TABLE':
            return DeltaLakeTableToJSON(value);
        case 'HIVE_DATABASE':
            return HiveDatabaseToJSON(value);
        case 'HIVE_TABLE':
            return HiveTableToJSON(value);
        case 'ICEBERG_SNAPSHOT':
            return IcebergSnapshotToJSON(value);
        case 'VIEW':
            return SqlViewToJSON(value);
        default:
            throw new Error(`No variant of Contents exists with 'type=${value['type']}'`);
    }
}

