/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Reference,
    ReferenceFromJSON,
    ReferenceFromJSONTyped,
    ReferenceToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateReference
 */
export interface CreateReference {
    /**
     * 
     * @type {string}
     * @memberof CreateReference
     */
    sourceRef?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateReference
     */
    hash?: any | null;
    /**
     * 
     * @type {Reference}
     * @memberof CreateReference
     */
    reference: Reference;
}

export function CreateReferenceFromJSON(json: any): CreateReference {
    return CreateReferenceFromJSONTyped(json, false);
}

export function CreateReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceRef': !exists(json, 'sourceRef') ? undefined : json['sourceRef'],
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'reference': ReferenceFromJSON(json['reference']),
    };
}

export function CreateReferenceToJSON(value?: CreateReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sourceRef': value.sourceRef,
        'hash': value.hash,
        'reference': ReferenceToJSON(value.reference),
    };
}


