/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Dialect {
    Dremio = 'DREMIO',
    Hive = 'HIVE',
    Presto = 'PRESTO',
    Spark = 'SPARK'
}

export function DialectFromJSON(json: any): Dialect {
    return DialectFromJSONTyped(json, false);
}

export function DialectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dialect {
    return json as Dialect;
}

export function DialectToJSON(value?: Dialect | null): any {
    return value as any;
}

