/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IcebergTable,
    IcebergTableFromJSONTyped,
    IcebergTableToJSON,
} from './';

/**
 * @type GlobalContents
 * 
 * @export
 */
export type GlobalContents = { type: 'ICEBERG_TABLE' } & IcebergTable;

export function GlobalContentsFromJSON(json: any): GlobalContents {
    return GlobalContentsFromJSONTyped(json, false);
}

export function GlobalContentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalContents {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'ICEBERG_TABLE':
            return {...IcebergTableFromJSONTyped(json, true), type: 'ICEBERG_TABLE'};
        default:
            throw new Error(`No variant of GlobalContents exists with 'type=${json['type']}'`);
    }
}

export function GlobalContentsToJSON(value?: GlobalContents | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'ICEBERG_TABLE':
            return IcebergTableToJSON(value);
        default:
            throw new Error(`No variant of GlobalContents exists with 'type=${value['type']}'`);
    }
}

