/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HiveDatabase
 */
export interface HiveDatabase {
    /**
     * 
     * @type {string}
     * @memberof HiveDatabase
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HiveDatabase
     */
    databaseDefinition?: Array<string>;
}

export function HiveDatabaseFromJSON(json: any): HiveDatabase {
    return HiveDatabaseFromJSONTyped(json, false);
}

export function HiveDatabaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HiveDatabase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'databaseDefinition': !exists(json, 'databaseDefinition') ? undefined : json['databaseDefinition'],
    };
}

export function HiveDatabaseToJSON(value?: HiveDatabase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'databaseDefinition': value.databaseDefinition,
    };
}


