/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents the global state of an Iceberg table in Nessie. An Iceberg table is globally identified via its fully qualified name via 'ContentsKey' plus a unique ID, the latter is represented via 'Contents.id'.
 * 
 * A Nessie commit-operation, performed via 'TreeApi.commitMultipleOperations', for Iceberg for Iceberg consists of a 'Operation.Put' with an 'IcebergSnapshot' and an 'IcebergTable' as the expected-global-state.
 * 
 * During a commit-operation, Nessie checks whether the known global state of the Iceberg table is compatible (think: equal) to 'Operation.Put.expectedContents'.
 * @export
 * @interface IcebergTable
 */
export interface IcebergTable {
    /**
     * 
     * @type {string}
     * @memberof IcebergTable
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IcebergTable
     */
    metadataLocation: string;
}

export function IcebergTableFromJSON(json: any): IcebergTable {
    return IcebergTableFromJSONTyped(json, false);
}

export function IcebergTableFromJSONTyped(json: any, ignoreDiscriminator: boolean): IcebergTable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'metadataLocation': json['metadataLocation'],
    };
}

export function IcebergTableToJSON(value?: IcebergTable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'metadataLocation': value.metadataLocation,
    };
}


