/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export function InstantFromJSON(json: any): Date {
    return InstantFromJSONTyped(json, false);
}

export function InstantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Date {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return new Date(json);
}

export function InstantToJSON(value?: Date | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return value.toISOString();
}
