/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommitMeta,
    CommitMetaFromJSON,
    CommitMetaFromJSONTyped,
    CommitMetaToJSON,
} from './';

/**
 * 
 * @export
 * @interface LogResponse
 */
export interface LogResponse {
    /**
     * 
     * @type {string}
     * @memberof LogResponse
     */
    token?: string;
    /**
     * 
     * @type {Array<CommitMeta>}
     * @memberof LogResponse
     */
    operations?: Array<CommitMeta>;
}

export function LogResponseFromJSON(json: any): LogResponse {
    return LogResponseFromJSONTyped(json, false);
}

export function LogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'operations': !exists(json, 'operations') ? undefined : ((json['operations'] as Array<any>).map(CommitMetaFromJSON)),
    };
}

export function LogResponseToJSON(value?: LogResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'operations': value.operations === undefined ? undefined : ((value.operations as Array<any>).map(CommitMetaToJSON)),
    };
}


