/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Merge
 */
export interface Merge {
    /**
     * 
     * @type {string}
     * @memberof Merge
     */
    fromHash?: string;
}

export function MergeFromJSON(json: any): Merge {
    return MergeFromJSONTyped(json, false);
}

export function MergeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Merge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromHash': !exists(json, 'fromHash') ? undefined : json['fromHash'],
    };
}

export function MergeToJSON(value?: Merge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fromHash': value.fromHash,
    };
}


