/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NessieConfiguration
 */
export interface NessieConfiguration {
    /**
     * 
     * @type {string}
     * @memberof NessieConfiguration
     */
    defaultBranch?: string;
    /**
     * 
     * @type {string}
     * @memberof NessieConfiguration
     */
    version?: string;
}

export function NessieConfigurationFromJSON(json: any): NessieConfiguration {
    return NessieConfigurationFromJSONTyped(json, false);
}

export function NessieConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): NessieConfiguration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaultBranch': !exists(json, 'defaultBranch') ? undefined : json['defaultBranch'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function NessieConfigurationToJSON(value?: NessieConfiguration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'defaultBranch': value.defaultBranch,
        'version': value.version,
    };
}


