/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Transplant
 */
export interface Transplant {
    /**
     * 
     * @type {string}
     * @memberof Transplant
     */
    sourceRef?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof Transplant
     */
    hashesToTransplant: Set<string>;
}

export function TransplantFromJSON(json: any): Transplant {
    return TransplantFromJSONTyped(json, false);
}

export function TransplantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transplant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceRef': !exists(json, 'sourceRef') ? undefined : json['sourceRef'],
        'hashesToTransplant': json['hashesToTransplant'],
    };
}

export function TransplantToJSON(value?: Transplant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sourceRef': value.sourceRef,
        'hashesToTransplant': value.hashesToTransplant,
    };
}


