/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Type {
    DELTALAKETABLE = 'DELTA_LAKE_TABLE',
    HIVEDATABASE = 'HIVE_DATABASE',
    HIVETABLE = 'HIVE_TABLE',
    ICEBERGTABLE = 'ICEBERG_TABLE',
    UNKNOWN = 'UNKNOWN',
    VIEW = 'VIEW'
}

export function TypeFromJSON(json: any): Type {
    return TypeFromJSONTyped(json, false);
}

export function TypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Type {
    return json as Type;
}

export function TypeToJSON(value?: Type | null): any {
    return value as any;
}

