/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContentsKey,
    ContentsKeyFromJSON,
    ContentsKeyFromJSONTyped,
    ContentsKeyToJSON,
} from './';

/**
 * 
 * @export
 * @interface Unchanged
 */
export interface Unchanged {
    /**
     * 
     * @type {ContentsKey}
     * @memberof Unchanged
     */
    key: ContentsKey;
}

export function UnchangedFromJSON(json: any): Unchanged {
    return UnchangedFromJSONTyped(json, false);
}

export function UnchangedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Unchanged {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': ContentsKeyFromJSON(json['key']),
    };
}

export function UnchangedToJSON(value?: Unchanged | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': ContentsKeyToJSON(value.key),
    };
}


