/*
 * Copyright (C) 2020 Dremio
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import java.nio.file.{Path, Paths}

/** Class generated by the Maven archetype for Gatling.
  */
object IDEPathHelper {

  private val projectRootDir = Paths
    .get(getClass.getClassLoader.getResource("gatling.conf").toURI)
    .getParent
    .getParent
    .getParent
    .getParent
  private val gradleBuildDirectory = projectRootDir.resolve("build")
  private val gatlingSrcDirectory =
    projectRootDir.resolve("src").resolve("gatling")

  val gradleSourcesDirectory: Path = gatlingSrcDirectory.resolve("scala")
  val gradleResourcesDirectory: Path = gatlingSrcDirectory.resolve("resources")
  val gradleBinariesDirectory: Path =
    gradleBuildDirectory.resolve("classes").resolve("scala").resolve("gatling")
  val resultsDirectory: Path =
    gradleBuildDirectory.resolve("reports").resolve("gatling")
  val recorderConfigFile: Path =
    gradleResourcesDirectory.resolve("recorder.conf")
}
